In [1]:
%matplotlib inline
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt







### How likely is it that you roll doubles when rolling two dice?
### 

16 percent

In [2]:
n_trials = nrows = 10_000
n_dice = ncols = 2

rolls = np.random.choice([1, 2, 3, 4, 5, 6], n_trials * n_dice).reshape(nrows, ncols)
rolls

array([[1, 4],
       [4, 4],
       [4, 3],
       ...,
       [1, 6],
       [6, 2],
       [4, 3]])

### If you flip 8 coins, what is the probability of getting exactly 3 heads? What is the probability of getting more than 3 heads?
### 

In [3]:

num_trials= 10000
num_coins = 8


heads =1
tails =0

outcomes=[heads, tails]

In [4]:
flips= np.random.choice(outcomes, size =(num_trials, num_coins))
flips

array([[0, 1, 0, ..., 1, 0, 1],
       [0, 0, 1, ..., 1, 1, 0],
       [1, 0, 1, ..., 1, 1, 1],
       ...,
       [1, 1, 0, ..., 1, 1, 0],
       [1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 1]])

In [5]:
num_heads = flips.sum(axis=1)
num_heads

array([3, 5, 7, ..., 5, 4, 4])

In [6]:
probability=(num_heads == 3).mean()
probability

0.2056

### MORE THAN 3


In [7]:
probabiltyb=(num_heads > 3).mean()
probability

0.2056

### There are approximitely 3 web development cohorts for every 1 data science cohort at Codeup. Assuming that Codeup randomly selects an alumni to put on a billboard, what are the odds that the two billboards I drive past both have data science students on them?
### 

In [8]:
webdevelopment = 0.75 
datascience = 0.25 
num_trials = 10000 
num_billboards = 2 

In [9]:
boards = np.random.random((num_trials, num_billboards))
boards

array([[0.51956322, 0.51895829],
       [0.86002192, 0.53445176],
       [0.57634717, 0.24058171],
       ...,
       [0.91832534, 0.07267858],
       [0.63528202, 0.48535847],
       [0.92132728, 0.68932233]])

In [10]:
DS_billboard = boards < datascience
DS_billboard

array([[False, False],
       [False, False],
       [False,  True],
       ...,
       [False,  True],
       [False, False],
       [False, False]])

In [11]:
(DS_billboard.sum(axis=1)==2).mean() 

0.0648

In [12]:
datascience = 1/4
webdevelopment = 3/4
outcome = [datascience, webdevelopment]

In [13]:
billboard = np.random.choice(outcome, size = (num_trials, num_billboards), p = [3/4, 1/4])


billboard = pd.DataFrame(billboard)
billboard.head()

0     1
0  0.25  0.25
1  0.25  0.25
2  0.25  0.25
3  0.25  0.25
4  0.25  0.25

In [14]:
billboard["num_ds"] = (billboard == 0.25).sum(axis=1)
(billboard.num_ds == 2).mean()


0.5649

### Codeup students buy, on average, 3 poptart packages with a standard deviation of 1.5 a day from the snack vending machine. If on monday the machine is restocked with 17 poptart packages, how likely is it that I will be able to buy some poptarts on Friday afternoon? (Remember, if you have mean and standard deviation, use the np.random.normal) You'll need to make a judgement call on how to handle some of your values
### 

In [15]:
num_trials = 10000 
num_packages = 17 
num_days = 5 

packages = np.round(np.random.normal(3,1.5, (num_trials, num_days)))
packages

array([[3., 4., 1., 1., 3.],
       [1., 4., 2., 2., 3.],
       [4., 2., 4., 4., 3.],
       ...,
       [5., 4., 4., 2., 2.],
       [4., 2., 3., 4., 2.],
       [2., 2., 4., 0., 3.]])

In [16]:
package_purchased = np.where(packages < 0,0,packages)
package_purchased

array([[3., 4., 1., 1., 3.],
       [1., 4., 2., 2., 3.],
       [4., 2., 4., 4., 3.],
       ...,
       [5., 4., 4., 2., 2.],
       [4., 2., 3., 4., 2.],
       [2., 2., 4., 0., 3.]])

In [17]:
all_packages = package_purchased.sum(axis=1)
all_packages

array([12., 12., 17., ..., 17., 15., 11.])

In [18]:
package_left_friday = all_packages < 17
package_left_friday

array([ True,  True, False, ..., False,  True,  True])

In [19]:
prob_left_friday = package_left_friday.mean()
prob_left_friday


0.6643

### Compare Heights
### 

### Men have an average height of 178 cm and standard deviation of 8cm.
### 

In [20]:
men_avg= 178
men_std=8

### Women have a mean of 170, sd = 6cm.
### 

In [21]:
women_avg=170
women_std=6

### Since you have means and standard deviations, you can use np.random.normal to generate observations.
### 

In [22]:
num_trial = 10000

### If a man and woman are chosen at random, what is the likelihood the woman is taller than the man?
### 

In [23]:
size_men = np.random.normal(men_avg, men_std, n_trials)

In [24]:
size_women = np.random.normal(women_avg, women_std, n_trials)

In [25]:
calculated_prob = (size_women > size_men).mean()

#take a look
calculated_prob

0.2098

### When installing anaconda on a student's computer, there's a 1 in 250 chance that the download is corrupted and the installation fails. What are the odds that after having 50 students download anaconda, no one has an installation issue? 100 students?
### 

In [26]:
num_trial = 10000
prob_fail = 1/250
num_install = 50
fail = 1
succeed = 0
outcome = [fail, succeed]

In [27]:
installs = np.random.choice(outcome, size = (num_trial, num_install), p = [249/250, 1/250])
((installs < prob_fail).sum(axis=1)== 0).mean()

0.8156

##### 100 students

In [28]:
num_trial = 10000
prob_fail = 1/250
num_install = 100
fail = 1
succeed = 0
outcome = [fail, succeed]

In [29]:
installs = np.random.choice(outcome, size = (num_trial, num_install), p = [249/250, 1/250])
((installs < prob_fail).sum(axis=1)== 0).mean()

0.6745

### What is the probability that we observe an installation issue within the first 150 students that download anaconda?
### 

In [30]:
num_trial = 10000
prob_fail = 1/250
num_install = 150
fail = 1
succeed = 0
outcome = [fail, succeed]

In [31]:
installs = np.random.random((num_install,num_trial))

In [32]:
installs < prob_fail

array([[False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       ...,
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False]])

In [33]:
((installs < prob_fail).sum(axis=1)> 0).mean()

1.0

### How likely is it that 450 students all download anaconda without an issue?
### 

In [34]:
num_trial = 10000
prob_fail = 1/250
num_install = 450
fail = 1
succeed = 0
outcome = [fail, succeed]

In [35]:
installs = np.random.random((num_install,num_trial))

In [36]:
installs < prob_fail

array([[False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       ...,
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [ True, False, False, ..., False, False, False]])

In [37]:
((installs < prob_fail).sum(axis=1)== 0).mean()


0.0

### There's a 70% chance on any given day that there will be at least one food truck at Travis Park. However, you haven't seen a food truck there in 3 days. How unlikely is this?
### 

In [38]:
num_trial= 10000
num_day= 3
truck=1
no_truck=0
prob = 0.7

In [39]:
data= np.random.random((num_trial,num_day))

In [40]:
((data < prob).sum(axis=1)==0).mean()


0.0269

### How likely is it that a food truck will show up sometime this week?
### 

In [41]:
num_trial= 10000
days_left= 3 
truck=1
no_truck=0
truck_prob = 0.7



In [42]:
truck_day = np.random.random((num_trial,days_left))


In [43]:
prob = ((truck_day < truck_prob).sum(axis=1) >0).mean()
prob


0.9712

### If 23 people are in the same room, what are the odds that two of them share a birthday? What if it's 20 people? 40?

In [44]:
num_trial = 10000
num_people = 23
outcome = range(0,365)


In [45]:
birthd = np.random.choice(outcome, size=(num_trial, num_people))
birthd

array([[340, 341, 335, ..., 100, 314, 157],
       [175, 210, 283, ..., 294,   6, 355],
       [294, 336, 184, ..., 106, 355, 162],
       ...,
       [298, 217, 320, ...,  78, 339, 233],
       [ 10,  72, 161, ...,  70,  83, 195],
       [ 11,  57, 161, ...,  84,  91, 299]])

In [46]:
pd.DataFrame(birthd).nunique(axis = 1)


0       23
1       23
2       22
3       23
4       22
        ..
9995    23
9996    23
9997    23
9998    22
9999    22
Length: 10000, dtype: int64

In [47]:
(pd.DataFrame(birthd).nunique(axis = 1) < 23).mean()


0.5154

### 20 people


In [48]:
num_trial = 10000
num_people = 20
outcome = range(0,365)

In [49]:
birthd = np.random.choice(outcome, size=(num_trial, num_people))
birthd

array([[108, 215, 124, ..., 218,  11,  47],
       [ 11, 181, 359, ...,  83, 262, 352],
       [126, 195, 216, ..., 200, 188, 100],
       ...,
       [324, 295, 276, ..., 246, 267,  56],
       [198,  61, 110, ..., 161,  54,  95],
       [284, 229, 287, ...,  52,   7, 252]])

In [50]:
pd.DataFrame(birthd).nunique(axis = 1)

0       19
1       20
2       20
3       20
4       20
        ..
9995    20
9996    18
9997    20
9998    19
9999    20
Length: 10000, dtype: int64

In [51]:
(pd.DataFrame(birthd).nunique(axis = 1) < 20).mean()


0.4056

### 40 people

In [52]:
num_trial = 10000
num_people = 40
outcome = range(0,365)


In [53]:
birthd = np.random.choice(outcome, size=(num_trial, num_people))
birthd

array([[108, 198, 228, ..., 244, 155,  63],
       [263,  37, 182, ...,  64, 273,  50],
       [127, 114, 317, ..., 256, 238, 228],
       ...,
       [269, 144, 334, ...,  99, 296,  99],
       [339, 143, 289, ..., 347, 137,  33],
       [196, 325, 287, ...,  11,  74,  84]])

In [54]:
pd.DataFrame(birthd).nunique(axis = 1)

0       38
1       37
2       38
3       36
4       36
        ..
9995    37
9996    35
9997    36
9998    39
9999    39
Length: 10000, dtype: int64

In [55]:
(pd.DataFrame(birthd).nunique(axis = 1) < 40).mean()


0.8959